#crie um programa que leia dois números e mostre a soma entre eles (sem copiar!)
n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
soma = (n1+n2)
print('A soma entre {} e {} resulta em {}'.format(n1,n2,soma))
